### PR TITLE
Demonstrate smoke test with Testcontainers

### PR DESCRIPTION
**Pull request by Tillerino**
Here, we show how smoke tests could be automated further with Testcontainers.

I disabled all except two tests to prove the concept. The idea is to run the smoke tests in the integration tests (failsafe plugin) and start Elasticsearch in Docker which will ultimately allow running them in CI. I customized two tests - one loading a configuration programatically and one loading configuration from a file - both works just fine.

I noticed two things:
- The smoke tests are really long. Obviously, this is not ideal for CI. I feel like 100k messages instead of 1M messages would prove the same point.
- The smoke tests don't really assert much. Ideally, they would check with elasticsearch if everything actually worked as intended. This would be easy with RestAssured or something - query `/index-name/_search` and check that `_hits` is 1000000 or something.

Testcontainers by default only run as long as the JVM does. Since maven forks JVMs for tests by default, they will be recreated for every module. However, containers can be reused (see example command below), which I find ideal. One would have to make sure to either use disjoint indices, index templates, component templates, etc. for all the tests or to clean up before/after tests which can also be done via RestAssured or a similar library. Alternatively, one could start a new container for every test as described [here](https://www.testcontainers.org/test_framework_integration/junit_5/). Depending on how fast the tests are overall, this could be an option.

The tests will run in the regular lifecycle, e.g. `mvn verify`. To only run the smoke tests, try `TESTCONTAINERS_REUSE_ENABLE=true mvn clean test-compile failsafe:integration-test failsafe:verify --fail-at-end`. This will also mark the Elasticsearch as reusable, which will mean it has to be stopped manually.

### CODE REVIEW

**Comment by rfoltyns** [comment]
Looks promising. I'll play around with it for a few days and add a few tweaks.

Let's start with testing it out in separate profiles for now:
* `e2e` for a few documents and to get things running, prepare datasets, assertions, debug. Run in CI once it's well prepared.
* `load` for current defaults (and convenience)

> maven forks JVMs for tests by default, they will be recreated for every module

That's good! :+1: Every suite should stop the container anyway.

> This will also mark the Elasticsearch as reusable, which will mean it has to be stopped manually
 
`-jest` and `-hc` are good candiates to test it out. Suite lifecycle should work nicely here. Also, whole container code can be moved to submodules, allow per-module config and get closer to 'interested code'. And base will still be only about Log4j2 stuff.

> RestAssured or something - query /index-name/_search and check that _hits is 1000000

Good idea :+1: But not RestAssured. Let's not mix stacks. Also, anything but Groovy :smile: Any http assertions based on Apache HC will be fine for `-jest` and `-hc`.
`*-bulkprocessor` can use `TransportClient.admin()` - verification should be trivial.

**Comment by rfoltyns** [comment]
I've started some prep.

* I'd like to run this against several versions of ES, so I just added `e2e` profile so that it doesn't run in CI. It might take a really long time to finish - container starts in ~20 seconds. Testing 4 versions (2.x, 5.x, 6.x, 7.x) and 3 security configs for both `hc` and `jest` (insecure/PEM/JKS) requires 24 runs. 2 run for each bulkprocessor security setup, that 6, so 30*20 = 600 seconds assuming that container would run per suite. That too expensive for Travis right now.
* All test certs were refreshed
* Version compatibility was an issue, mainly around index templates and feature support between versions, so `smokeTest.api.version` was added

Next steps:
* ES containers will need more config and initial setup. I'll probably push some config files later: elasticsearch.yml, users, user_roles, role_mapping, elasticsearch-keystore, etc.
* In order to test against multiple versions with `hc` and `jest` some sort of additional parametrization is needed. I have some ideas. It may take a while though

**Comment by rfoltyns** [comment]
I have some work to commit within the scope of this PR, but I can't commit to your repo.. Could you setup permissions on your fork, please?

**Comment by Tillerino** [comment]
Weird. Usually you would be able to push to the branch at least. I added you as a collaborator 🤷‍♀️

**Comment by rfoltyns** [comment]
Yeah, it's weird. Maybe a combination of some general settings on our accounts..

**Comment by rfoltyns** [comment]
I've implemented a few changes I mentioned above. I'll pull out the config bits as an independent commit. 

`ContainerRunner` was the main goal here - isolating the whole container setup somehow. What do you think?

**Comment by rfoltyns** [comment]
Ok. That's most probably my last batch of updates for now:

* ES can now run with any containerized version
* Security can be toggled

You can try it out with:

`mvn -P e2e clean install -pl log4j2-elasticsearch-hc -Dtest=SmokeTest#programmaticConfigTest -DsmokeTest.containers.enabled=true -DsmokeTest.secure=true -DsmokeTest.api.version=7.10.2`

(or `-DsmokeTest.api.version=5.6.16` or any other) 

Would you like to continue on your own or should I just wrap it up outside of this PR? Jest and bulkprocessors need similar changes. Also, there's no verification yet.

**Comment by Tillerino** [comment]
Hi rfoltyns,

Sorry I guess my description was open to interpretation. I did not plan on finishing this MR myself. I just wanted to demonstrate the mechanism so that you could evaluate it and decide if it works for your project - which it looks like it does :)

So just do anything you want with this. I guess you already polished this to a level where you'd be comfortable merging and using it.

**Comment by rfoltyns** [comment]
@Tillerino It works nicely indeed.

Thanks for the update. I'm closing this PR then.

I'll add these tests in other scope. In current state, it's ~15-20% complete.

**Pull request closed without merging**
